In [1]:
import pandas as pd
import numpy as np

from utils.personal_utils import *

import mlflow
from tsfeatures import tsfeatures
import os

from utils.compression_algos import *

In [2]:
# Load Different Datasets to see how they are:

all_datasets = [
                "/home/sim/Desktop/TS Extrinsic Regression/data/AppliancesEnergy_TEST.ts", 
                "/home/sim/Desktop/TS Extrinsic Regression/data/BeijingPM25Quality_TEST.ts",
                "/home/sim/Desktop/TS Extrinsic Regression/data/IEEEPPG_TEST.ts",
                "/home/sim/Desktop/TS Extrinsic Regression/data/NewsTitleSentiment_TEST.ts",
                "/home/sim/Desktop/TS Extrinsic Regression/data/Covid3Month_TEST.ts",
                





                "/home/sim/Desktop/TS Extrinsic Regression/data/BenzeneConcentration_TEST.ts",
                "/home/sim/Desktop/TS Extrinsic Regression/data/FloodModeling1_TEST.ts",
                "/home/sim/Desktop/TS Extrinsic Regression/data/HouseholdPowerConsumption1_TEST.ts",
                ]
loaded_datasets = []

for dataset_path in all_datasets:
    loaded_datasets.append(load_dataset(dataset_path))


    print(os.path.basename(dataset_path).split('_')[0], " ", loaded_datasets[-1].shape)
                





66it [00:01, 51.56it/s] 
100%|██████████| 42/42 [00:00<00:00, 487.96it/s]


AppliancesEnergy   (42, 144, 24)


4097it [00:09, 412.09it/s]


KeyboardInterrupt: 

In [2]:
path = "/home/sim/Desktop/TS Extrinsic Regression/data/IEEEPPG_TEST.ts"
a = load_dataset(path)

1351it [00:01, 691.05it/s]
100%|██████████| 1328/1328 [00:01<00:00, 1310.86it/s]


In [10]:
# Test if for even input coefficient array can have bigger size than normal!
# Test if decompressed array is bigger than input array -> For uneven inputs yes.

for i in range(0,2002,1):
    long_array = np.random.rand(i)
    

    if dwt_compress(long_array, 0.1, True,level=5, wavelet= "haar", quantization_level=16).shape[0] :#- i not in [0,1,2]:
        print(i, dwt_compress(long_array, 0.1, True,level=5, wavelet= "db4", quantization_level=16).shape[0] - i)



# Learned:(with max level and on input signal of size 2000)
# The decompressed signal is in every case max 1 bigger and only if it is uneven! -> Our Blocks are always even. No Problem.
# The coefficients/ compressed signal and with max_level can be up to 2,3,4 bigger. Also for signals of length < 2000. On it's way to 2000 it can even get up to 7.


1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 0
14 0
15 1
16 0
17 1
18 0
19 1
20 0
21 1
22 0
23 1
24 0
25 1
26 0
27 1
28 0
29 1
30 0
31 1
32 0
33 1
34 0
35 1
36 0
37 1
38 0
39 1
40 0
41 1
42 0
43 1
44 0
45 1
46 0
47 1
48 0
49 1
50 0
51 1
52 0
53 1
54 0
55 1
56 0
57 1
58 0
59 1
60 0
61 1
62 0
63 1
64 0
65 1
66 0
67 1
68 0
69 1
70 0
71 1
72 0
73 1
74 0
75 1
76 0
77 1
78 0
79 1
80 0
81 1
82 0
83 1
84 0
85 1
86 0
87 1
88 0
89 1
90 0
91 1
92 0
93 1
94 0
95 1
96 0
97 1
98 0
99 1
100 0
101 1
102 0
103 1
104 0
105 1
106 0
107 1
108 0
109 1
110 0
111 1
112 0
113 1
114 0
115 1
116 0
117 1
118 0
119 1
120 0
121 1
122 0
123 1
124 0
125 1
126 0
127 1
128 0
129 1
130 0
131 1
132 0
133 1
134 0
135 1
136 0
137 1
138 0
139 1
140 0
141 1
142 0
143 1
144 0
145 1
146 0
147 1
148 0
149 1
150 0
151 1
152 0
153 1
154 0
155 1
156 0
157 1
158 0
159 1
160 0
161 1
162 0
163 1
164 0
165 1
166 0
167 1
168 0
169 1
170 0
171 1
172 0
173 1
174 0
175 1
176 0
177 1
178 0
179 1
180 0
181 1
182 0
183 1
184 0
185 

In [4]:
# Test dimension flattening for compresssion
import numpy as np

# Define the array dimensions
num_dp = 6
len_ts = 3
dim = 4

# Create an example array with shape (6, 3, 4)
data = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ],
    [
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]
    ],
    [
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]
    ],
    [
        [49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60]
    ],
    [
        [61, 62, 63, 64],
        [65, 66, 67, 68],
        [69, 70, 71, 72]
    ]
])

print("Original array:")
print(data)
print("Original shape:", data.shape)
# Output: (6, 3, 4)

# Reshape the array to (num_dp * len_ts, dim)
flattened_data = data.reshape(-1, dim)

print("\nFlattened array:")
print(flattened_data)
print("New shape:", flattened_data.shape)
# Output: (18, 4)


Original array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]

 [[37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]]

 [[61 62 63 64]
  [65 66 67 68]
  [69 70 71 72]]]
Original shape: (6, 3, 4)

Flattened array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]
 [41 42 43 44]
 [45 46 47 48]
 [49 50 51 52]
 [53 54 55 56]
 [57 58 59 60]
 [61 62 63 64]
 [65 66 67 68]
 [69 70 71 72]]
New shape: (18, 4)
